<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class TRANING extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('TRANING_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'traning/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'traning/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'traning/index.html';
            $config['first_url'] = base_url() . 'traning/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->TRANING_model->total_rows($q);
        $traning = $this->TRANING_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'traning_data' => $traning,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('traning/TRANING_list', $data);
    }

    public function read($id) 
    {
        $row = $this->TRANING_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID_TRANING' => $row->ID_TRANING,
		'TOPIK_TRANING' => $row->TOPIK_TRANING,
		'ID_BLOG' => $row->ID_BLOG,
	    );
            $this->load->view('traning/TRANING_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('traning'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('traning/create_action'),
	    'ID_TRANING' => set_value('ID_TRANING'),
	    'TOPIK_TRANING' => set_value('TOPIK_TRANING'),
	    'ID_BLOG' => set_value('ID_BLOG'),
	);
        $this->load->view('traning/TRANING_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'TOPIK_TRANING' => $this->input->post('TOPIK_TRANING',TRUE),
		'ID_BLOG' => $this->input->post('ID_BLOG',TRUE),
	    );

            $this->TRANING_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('traning'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->TRANING_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('traning/update_action'),
		'ID_TRANING' => set_value('ID_TRANING', $row->ID_TRANING),
		'TOPIK_TRANING' => set_value('TOPIK_TRANING', $row->TOPIK_TRANING),
		'ID_BLOG' => set_value('ID_BLOG', $row->ID_BLOG),
	    );
            $this->load->view('traning/TRANING_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('traning'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID_TRANING', TRUE));
        } else {
            $data = array(
		'TOPIK_TRANING' => $this->input->post('TOPIK_TRANING',TRUE),
		'ID_BLOG' => $this->input->post('ID_BLOG',TRUE),
	    );

            $this->TRANING_model->update($this->input->post('ID_TRANING', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('traning'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->TRANING_model->get_by_id($id);

        if ($row) {
            $this->TRANING_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('traning'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('traning'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('TOPIK_TRANING', 'topik traning', 'trim|required');
	$this->form_validation->set_rules('ID_BLOG', 'id blog', 'trim|required');

	$this->form_validation->set_rules('ID_TRANING', 'ID_TRANING', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file TRANING.php */
/* Location: ./application/controllers/TRANING.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-18 18:51:17 */
/* http://harviacode.com */