<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class TUGAS extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('TUGAS_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'tugas/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'tugas/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'tugas/index.html';
            $config['first_url'] = base_url() . 'tugas/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->TUGAS_model->total_rows($q);
        $tugas = $this->TUGAS_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'tugas_data' => $tugas,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('tugas/TUGAS_list', $data);
    }

    public function read($id) 
    {
        $row = $this->TUGAS_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID_TUGAS' => $row->ID_TUGAS,
		'DATE_LINE' => $row->DATE_LINE,
		'ID_JOB' => $row->ID_JOB,
	    );
            $this->load->view('tugas/TUGAS_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tugas'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tugas/create_action'),
	    'ID_TUGAS' => set_value('ID_TUGAS'),
	    'DATE_LINE' => set_value('DATE_LINE'),
	    'ID_JOB' => set_value('ID_JOB'),
	);
        $this->load->view('tugas/TUGAS_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'DATE_LINE' => $this->input->post('DATE_LINE',TRUE),
		'ID_JOB' => $this->input->post('ID_JOB',TRUE),
	    );

            $this->TUGAS_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tugas'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->TUGAS_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tugas/update_action'),
		'ID_TUGAS' => set_value('ID_TUGAS', $row->ID_TUGAS),
		'DATE_LINE' => set_value('DATE_LINE', $row->DATE_LINE),
		'ID_JOB' => set_value('ID_JOB', $row->ID_JOB),
	    );
            $this->load->view('tugas/TUGAS_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tugas'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID_TUGAS', TRUE));
        } else {
            $data = array(
		'DATE_LINE' => $this->input->post('DATE_LINE',TRUE),
		'ID_JOB' => $this->input->post('ID_JOB',TRUE),
	    );

            $this->TUGAS_model->update($this->input->post('ID_TUGAS', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tugas'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->TUGAS_model->get_by_id($id);

        if ($row) {
            $this->TUGAS_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tugas'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tugas'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('DATE_LINE', 'date line', 'trim|required');
	$this->form_validation->set_rules('ID_JOB', 'id job', 'trim|required');

	$this->form_validation->set_rules('ID_TUGAS', 'ID_TUGAS', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file TUGAS.php */
/* Location: ./application/controllers/TUGAS.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-18 18:51:17 */
/* http://harviacode.com */