<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class RAPORT extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('RAPORT_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'raport/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'raport/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'raport/index.html';
            $config['first_url'] = base_url() . 'raport/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->RAPORT_model->total_rows($q);
        $raport = $this->RAPORT_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'raport_data' => $raport,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('raport/RAPORT_list', $data);
    }

    public function read($id) 
    {
        $row = $this->RAPORT_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID_RAPORT' => $row->ID_RAPORT,
		'ID_KELAS' => $row->ID_KELAS,
		'ID_JOB' => $row->ID_JOB,
	    );
            $this->load->view('raport/RAPORT_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('raport'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('raport/create_action'),
	    'ID_RAPORT' => set_value('ID_RAPORT'),
	    'ID_KELAS' => set_value('ID_KELAS'),
	    'ID_JOB' => set_value('ID_JOB'),
	);
        $this->load->view('raport/RAPORT_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'ID_KELAS' => $this->input->post('ID_KELAS',TRUE),
		'ID_JOB' => $this->input->post('ID_JOB',TRUE),
	    );

            $this->RAPORT_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('raport'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->RAPORT_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('raport/update_action'),
		'ID_RAPORT' => set_value('ID_RAPORT', $row->ID_RAPORT),
		'ID_KELAS' => set_value('ID_KELAS', $row->ID_KELAS),
		'ID_JOB' => set_value('ID_JOB', $row->ID_JOB),
	    );
            $this->load->view('raport/RAPORT_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('raport'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID_RAPORT', TRUE));
        } else {
            $data = array(
		'ID_KELAS' => $this->input->post('ID_KELAS',TRUE),
		'ID_JOB' => $this->input->post('ID_JOB',TRUE),
	    );

            $this->RAPORT_model->update($this->input->post('ID_RAPORT', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('raport'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->RAPORT_model->get_by_id($id);

        if ($row) {
            $this->RAPORT_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('raport'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('raport'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('ID_KELAS', 'id kelas', 'trim|required');
	$this->form_validation->set_rules('ID_JOB', 'id job', 'trim|required');

	$this->form_validation->set_rules('ID_RAPORT', 'ID_RAPORT', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file RAPORT.php */
/* Location: ./application/controllers/RAPORT.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-20 11:42:29 */
/* http://harviacode.com */